---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: 'trippsc2.test'
jobs:
  molecule:
    name: Molecule
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      matrix:
        box:
          - debian12_base
          - fedora42_base
          - fedora41_base
          - rocky9_base
          - rocky9_cis
          - rocky9_ws_base
          - rocky8_base
          - rocky8_cis
          - rocky8_ws_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.test'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          molecule test
          deactivate
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_BOX: ${{ matrix.box }}
