---
name: Release
'on':
  push:
    tags:
      - '*'
defaults:
  run:
    working-directory: 'trippsc2.test'
jobs:
  release:
    name: Release
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.test'
      - name: Release
        run: |
          source ~/venv/ansible-2.16/bin/activate
          ansible-galaxy collection build --force
          ansible-galaxy collection publish --force --token "$ANSIBLE_GALAXY_TOKEN" *.tar.gz
          rm -rf *.tar.gz
          deactivate
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.GALAXY_API_KEY }}
