---
name: Release collection
'on':
  push:
    tags:
      - '*'
defaults:
  run:
    working-directory: 'trippsc2.test'
jobs:
  release:
    name: Release
    runs-on:
      - self-hosted
      - linux
      - x64
    permissions:
      contents: write
    steps:
      - name: Release collection
        uses: trippsoft/github-actions/.github/workflows/release.yml@main
        with:
          working_directory: 'trippsc2.test'
